server:
  cors:
    origin:
      - "http://localhost:3001"
    methods: "GET,HEAD,PUT,PATCH,DELETE"
    credentials: true

db:
  host: "localhost"
  username: "root"
  password: "123456"
  synchronize: true
